"""Initial migration

Revision ID: 99e6b5897ab2
Revises: 
Create Date: 2024-11-17 22:43:09.110738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e6b5897ab2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('egreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('subcategoria', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('recurrente', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bancos', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otro_ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=70), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago_recurrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_recurrente')
    op.drop_table('otro_ingreso')
    op.drop_table('ingreso')
    op.drop_table('egreso')
    op.drop_table('user')
    # ### end Alembic commands ###
