"""Add descripcion to Ingreso

Revision ID: f1e5098c2622
Revises: 
Create Date: 2024-11-11 23:00:07.736489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e5098c2622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingreso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingreso', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
